import React, { createContext, useContext, useState, useEffect } from 'react';

interface Language {
  code: string;
  name: string;
  flag: string;
  direction: 'ltr' | 'rtl';
}

export const languages: Language[] = [
  { code: 'pt', name: 'Português', flag: '🇧🇷', direction: 'ltr' },
  { code: 'en', name: 'English', flag: '🇺🇸', direction: 'ltr' },
  { code: 'es', name: 'Español', flag: '🇪🇸', direction: 'ltr' },
  { code: 'zh', name: '中文', flag: '🇨🇳', direction: 'ltr' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳', direction: 'ltr' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', direction: 'rtl' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩', direction: 'ltr' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺', direction: 'ltr' },
  { code: 'ja', name: '日本語', flag: '🇯🇵', direction: 'ltr' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', direction: 'ltr' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', direction: 'ltr' }
];

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Traduções completas para todos os idiomas
const translations: Record<string, Record<string, string>> = {
  pt: {
    // Navegação
    'nav.home': 'Início',
    'nav.acupressure': 'Acupressão',
    'nav.breathing': 'Respiração',
    'nav.premium': 'Premium',
    'nav.corporate': 'Corporativo',
    'nav.dashboard': 'Dashboard',
    'nav.sounds': 'Sons',
    'nav.progress': 'Progresso',
    'nav.personalization': 'Personalização',
    'nav.login': 'Entrar',
    'nav.logout': 'Sair',

    // Home
    'home.hero.title': 'Evolua',
    'home.hero.subtitle': 'Harmonize sua energia Viva com Leveza',
    'home.hero.startNow': 'Começar Agora',
    'home.hero.createAccount': 'Criar Conta',
    'home.features.title': 'Recursos Completos',
    'home.features.subtitle': 'Acupressão MTC e Craniopuntura: Através de sequências guiadas, você aplica toques terapêuticos em pontos específicos do corpo e da cabeça. Respiração 4-7-8 Trabalha o SNC controla o estresse, reduz a ansiedade.',
    'home.feature.acupressure.title': 'Acupressão MTC',
    'home.feature.acupressure.desc': '20 pontos terapêuticos da Medicina Tradicional Chinesa',
    'home.feature.cranio.title': 'Craniopuntura',
    'home.feature.cranio.desc': 'Técnicas cranianas para memória, concentração e ansiedade',
    'home.feature.breathing.title': 'Respiração 4-7-8',
    'home.feature.breathing.desc': 'Técnica científica com timer e cromoterapia integrada',
    'home.feature.chromotherapy.title': 'Cromoterapia',
    'home.feature.chromotherapy.desc': 'Cores terapêuticas baseadas em neurociência',
    'home.feature.sounds.title': 'Sons Harmonizantes',
    'home.feature.sounds.desc': 'Biblioteca completa + integração Spotify Premium',
    'home.feature.consultation.title': 'Consultas WhatsApp',
    'home.cta.title': 'Pronto para começar?',
    'home.cta.subtitle': 'Junte-se a milhares de pessoas transformando suas vidas',
    'home.cta.demo': 'Experimentar Grátis',
    'home.cta.corporate': 'Soluções Corporativas',
    'home.compliance.title': 'Compliance Legal Corporativo',
    'home.compliance.subtitle': 'Atendimento integral à legislação brasileira',

    // Acupressure page
    'acupressure.title': 'Terapia Integrada',
    'acupressure.subtitle': 'Acupressão + Respiração 4-7-8 + Cromoterapia + Sons Harmonizantes',
    'acupressure.categories.all': 'Todos os Pontos',
    'acupressure.categories.general': 'MTC Geral',
    'acupressure.categories.cranio': 'Craniopuntura',
    'acupressure.categories.septicemia': 'Septicemia',
    'acupressure.categories.atm': 'ATM',
    'acupressure.point.benefits': 'Para que serve',
    'acupressure.point.location': 'Localização',
    'acupressure.point.instructions': 'Como aplicar',
    'acupressure.point.duration': 'Duração',
    'acupressure.point.pressure': 'Pressão',
    'acupressure.timer.active': 'Terapia Ativa',
    'acupressure.timer.start': 'Iniciar Terapia Integrada',
    'acupressure.timer.stop': 'Parar',
    'acupressure.timer.reset': 'Reiniciar',
    'acupressure.timer.switch': 'Trocar para Este Ponto',
    'acupressure.premium.unlock': 'Desbloquear Premium',
    'acupressure.premium.exclusive': 'Ponto Premium',
    'acupressure.select.title': 'Selecione um Ponto',
    'acupressure.select.subtitle': 'Clique em qualquer ponto para iniciar a terapia integrada completa',
    'acupressure.integrated.description': 'Terapia Integrada: Acupressão com timer preciso, Respiração 4-7-8 sincronizada, Cromoterapia com cores vibrantes, Sons harmonizantes opcionais',

    // Corporate page
    'corporate.hero.title': 'Soluções Corporativas B2B',
    'corporate.hero.subtitle': 'Transforme o bem-estar da sua empresa com tecnologia e dados',
    'corporate.benefits.title': 'Por que escolher XZenPress B2B?',
    'corporate.benefits.compliance': 'Compliance Legal',
    'corporate.benefits.compliance.desc': 'Atendimento integral à Lei 14.831/2024 e NR-1',
    'corporate.benefits.roi': 'ROI Comprovado',
    'corporate.benefits.roi.desc': 'Retorno do investimento em 6 meses',
    'corporate.benefits.engagement': 'Engajamento',
    'corporate.benefits.engagement.desc': 'Aumento de 40% no bem-estar dos funcionários',
    'corporate.benefits.certification': 'Certificação',
    'corporate.benefits.certification.desc': 'Selo de Empresa Promotora da Saúde Mental',
    'corporate.plans.title': 'Planos Corporativos',
    'corporate.plans.subtitle': 'Soluções completas de bem-estar para empresas de todos os tamanhos',
    'corporate.analytics.title': 'Analytics B2B',
    'corporate.analytics.subtitle': 'Inteligência de dados para otimizar o bem-estar corporativo',
    'corporate.roi.title': 'ROI Comprovado',
    'corporate.roi.subtitle': 'Empresas que implementaram XZenPress relatam:',
    'corporate.roi.stress': 'Redução no estresse',
    'corporate.roi.absences': 'Menos afastamentos',
    'corporate.roi.engagement': 'Maior engajamento',
    'corporate.roi.return': 'Retorno do investimento',
    'corporate.contact.title': 'Pronto para transformar sua empresa?',
    'corporate.contact.subtitle': 'Fale com nossos especialistas e receba uma proposta personalizada',

    // Login
    'login.welcome': 'Bem-vindo de volta',
    'login.createAccount': 'Criar Conta',
    'login.subtitle.login': 'Entre na sua conta para continuar',
    'login.subtitle.register': 'Crie sua conta e comece sua jornada',
    'login.name': 'Nome Completo',
    'login.email': 'Email',
    'login.password': 'Senha',
    'login.confirmPassword': 'Confirmar Senha',
    'login.forgotPassword': 'Esqueci minha senha',
    'login.noAccount': 'Não tem conta? Criar uma',
    'login.hasAccount': 'Já tem conta? Entrar',
    'login.demo.title': 'Demonstração',
    'login.demo.desc': 'Use qualquer email válido + senha com 6+ caracteres',
    'login.reset.title': 'Recuperar Senha',
    'login.reset.subtitle': 'Digite seu email para receber instruções',
    'login.reset.send': 'Enviar Email',
    'login.reset.back': 'Voltar ao Login',

    // Respiração
    'breathing.title': 'Respiração 4-7-8',
    'breathing.inhale': 'Inspire',
    'breathing.hold': 'Segure',
    'breathing.exhale': 'Expire',
    'breathing.start': 'Iniciar',
    'breathing.stop': 'Parar',
    'breathing.reset': 'Reiniciar',
    'breathing.totalTime': 'Tempo Total',
    'breathing.phase': 'Fase',
    'breathing.phase.inhale.detail': 'Inspiração profunda pelo nariz',
    'breathing.phase.hold.detail': 'Retenção do ar nos pulmões',
    'breathing.phase.exhale.detail': 'Expiração lenta pela boca',
    'breathing.chromotherapy.title': 'Cromoterapia Científica',
    'breathing.chromotherapy.description': 'Cores terapêuticas sincronizadas com cada fase da respiração',
    'breathing.chromotherapy.blue': 'Azul Calmante',
    'breathing.chromotherapy.blue.desc': 'Reduz pressão arterial e ativa o sistema parassimpático',
    'breathing.chromotherapy.blue.short': 'Calmante',
    'breathing.chromotherapy.green': 'Verde Equilibrante',
    'breathing.chromotherapy.green.desc': 'Equilibra o sistema nervoso e harmoniza emoções',
    'breathing.chromotherapy.green.short': 'Equilibrante',
    'breathing.chromotherapy.magenta': 'Roxo Energizante',
    'breathing.chromotherapy.magenta.desc': 'Estimula a produção de endorfinas e libera tensões',
    'breathing.chromotherapy.magenta.short': 'Energizante',
    'breathing.benefits.title': 'Benefícios Científicos',
    'breathing.benefits.stress': 'Reduz cortisol',
    'breathing.benefits.sleep': 'Melhora sono',
    'breathing.benefits.focus': 'Aumenta foco',
    'breathing.benefits.pressure': 'Reduz pressão',
    'breathing.science.title': 'Base Científica',
    'breathing.science.evidence': 'Evidências Científicas',
    'breathing.science.parasympathetic': 'Ativa sistema parassimpático',
    'breathing.science.cortisol': 'Reduz cortisol em 23%',
    'breathing.science.heartRate': 'Diminui frequência cardíaca',
    'breathing.science.gaba': 'Aumenta GABA cerebral',
    'breathing.science.chromotherapy': 'Cromoterapia',
    'breathing.science.blue.effect': 'Azul reduz pressão arterial',
    'breathing.science.green.effect': 'Verde equilibra sistema nervoso',
    'breathing.science.magenta.effect': 'Roxo estimula endorfinas',
    'breathing.science.melatonin': 'Cores regulam melatonina',
    'breathing.sounds.title': 'Sons Harmonizantes',
    'breathing.sounds.free.title': 'Sons Gratuitos',
    'breathing.sounds.ocean': 'Sons do Mar',
    'breathing.sounds.ocean.desc': 'Ondas relaxantes',
    'breathing.sounds.rain': 'Chuva Suave',
    'breathing.sounds.rain.desc': 'Chuva calmante',
    'breathing.sounds.forest': 'Floresta',
    'breathing.sounds.fireplace': 'Lareira',
    'breathing.sounds.classical': 'Clássica',
    'breathing.sounds.mantras': 'Mantras',
    'breathing.sounds.more': '+45 sons',
    'breathing.sounds.play': 'Reproduzir',
    'breathing.sounds.pause': 'Pausar',
    'breathing.sounds.stop': 'Parar',
    'breathing.sounds.premium.title': 'Biblioteca Premium',
    'breathing.sounds.premium.desc': 'Mais de 50 sons exclusivos + integração Spotify',
    'breathing.sounds.premium.spotify': 'Abrir Spotify',
    'breathing.sounds.premium.upgrade': 'Upgrade Premium',

    // Premium
    'premium.hero.title': 'Desbloqueie Todo o Potencial',
    'premium.hero.subtitle': 'Acesso completo a consultas especializadas e pontos exclusivos',
    'premium.hero.active': 'Premium Ativo',
    'premium.hero.upgrade': 'Fazer Upgrade',
    'premium.features.title': 'Recursos Premium',
    'premium.features.available': 'Disponível',
    'premium.features.coming': 'Em Breve',
    'premium.features.whatsapp.title': 'Consultas WhatsApp',
    'premium.features.whatsapp.description': 'Atendimento especializado via WhatsApp',
    'premium.features.whatsapp.benefit1': 'Profissional com 15+ anos',
    'premium.features.whatsapp.benefit2': 'Resposta em até 2h',
    'premium.features.whatsapp.benefit3': 'Casos complexos',
    'premium.features.whatsapp.benefit4': 'Acompanhamento personalizado',
    'premium.features.points.title': 'Pontos Exclusivos',
    'premium.features.points.description': '11 pontos especializados premium',
    'premium.features.points.benefit1': 'Septicemia (3 pontos)',
    'premium.features.points.benefit2': 'ATM (3 pontos)',
    'premium.features.points.benefit3': 'Cranioterapia (3 pontos)',
    'premium.features.points.benefit4': 'Neurologia (2 pontos)',
    'premium.features.chromotherapy.title': 'Cromoterapia Avançada',
    'premium.features.chromotherapy.description': 'Sequências personalizadas de cores',
    'premium.features.chromotherapy.benefit1': 'Perfis adaptativos',
    'premium.features.chromotherapy.benefit2': 'Sincronização biofeedback',
    'premium.features.chromotherapy.benefit3': 'Cores personalizadas',
    'premium.features.chromotherapy.benefit4': 'Terapia integrada',
    'premium.features.sounds.title': 'Biblioteca Completa',
    'premium.features.sounds.description': '50+ sons + Spotify Premium',
    'premium.features.sounds.benefit1': 'Frequências binaurais',
    'premium.features.sounds.benefit2': 'Mantras sagrados',
    'premium.features.sounds.benefit3': 'Natureza HD',
    'premium.features.sounds.benefit4': 'Playlists curadas',
    'premium.features.ai.title': 'Recomendações IA',
    'premium.features.ai.description': 'Inteligência artificial personalizada',
    'premium.features.ai.benefit1': 'Análise de padrões',
    'premium.features.ai.benefit2': 'Sugestões personalizadas',
    'premium.features.ai.benefit3': 'Otimização automática',
    'premium.features.ai.benefit4': 'Insights preditivos',
    'premium.features.offline.title': 'Modo Offline',
    'premium.features.offline.description': 'Funcionalidades offline completas',
    'premium.features.offline.benefit1': 'Sincronização automática',
    'premium.features.offline.benefit2': 'Cache inteligente',
    'premium.features.offline.benefit3': 'Dados seguros',
    'premium.features.offline.benefit4': 'Acesso sem internet',
    'premium.plans.title': 'Planos Premium',
    'premium.plans.subtitle': 'Escolha o plano ideal para você',
    'premium.plans.popular': 'Mais Popular',
    'premium.plans.choose': 'Escolher Plano',
    'premium.plans.save': 'Economize',
    'premium.plans.monthly.name': 'Premium Mensal',
    'premium.plans.monthly.period': '/mês',
    'premium.plans.monthly.feature1': 'Consultas WhatsApp ilimitadas',
    'premium.plans.monthly.feature2': '11 pontos exclusivos',
    'premium.plans.monthly.feature3': 'Biblioteca completa de sons',
    'premium.plans.monthly.feature4': 'Cromoterapia avançada',
    'premium.plans.monthly.feature5': 'Suporte prioritário',
    'premium.plans.annual.name': 'Premium Anual',
    'premium.plans.annual.period': '/ano',
    'premium.plans.annual.feature1': 'Tudo do plano mensal',
    'premium.plans.annual.feature2': '2 meses grátis',
    'premium.plans.annual.feature3': 'Recomendações IA',
    'premium.plans.annual.feature4': 'Relatórios avançados',
    'premium.plans.annual.feature5': 'Acesso beta a novos recursos',
    'premium.plans.lifetime.name': 'Premium Vitalício',
    'premium.plans.lifetime.period': 'pagamento único',
    'premium.plans.lifetime.feature1': 'Acesso vitalício completo',
    'premium.plans.lifetime.feature2': 'Todos os recursos futuros',
    'premium.plans.lifetime.feature3': 'Suporte VIP',
    'premium.plans.lifetime.feature4': 'Consultoria personalizada',
    'premium.plans.lifetime.feature5': 'Sem mensalidades',
    'premium.payment.title': 'Finalizar Pagamento',
    'premium.payment.methods': 'Métodos de Pagamento',
    'premium.payment.pix': 'PIX',
    'premium.payment.pix.desc': 'Instantâneo',
    'premium.payment.pix.title': 'Pagamento via PIX',
    'premium.payment.credit': 'Cartão',
    'premium.payment.credit.desc': 'Visa, Master, Amex',
    'premium.payment.credit.title': 'Cartão de Crédito',
    'premium.payment.crypto': 'Crypto',
    'premium.payment.crypto.desc': 'Bitcoin, Ethereum',
    'premium.payment.crypto.title': 'Criptomoedas',
    'premium.payment.back': 'Voltar',
    'premium.payment.confirm': 'Confirmar Pagamento',
    'premium.testimonials.title': 'Depoimentos',
    'premium.testimonials.maria': 'Atendimento excepcional! Resolveu minha dor crônica em poucas sessões.',
    'premium.testimonials.joao': 'A plataforma mudou minha vida. Durmo melhor e tenho menos ansiedade.',
    'premium.testimonials.ana': 'Profissional muito competente. Recomendo para todos!',
    'premium.faq.title': 'Perguntas Frequentes',
    'premium.faq.q1': 'Como funciona o atendimento WhatsApp?',
    'premium.faq.a1': 'Você preenche um formulário detalhado e recebe atendimento personalizado via WhatsApp.',
    'premium.faq.q2': 'Posso cancelar a qualquer momento?',
    'premium.faq.a2': 'Sim, você pode cancelar sua assinatura a qualquer momento sem taxas.',
    'premium.faq.q3': 'Os pontos premium são seguros?',
    'premium.faq.a3': 'Todos os pontos são baseados na Medicina Tradicional Chinesa com supervisão profissional.',
    'premium.faq.q4': 'Quanto tempo para ver resultados?',
    'premium.faq.a4': 'A maioria dos usuários relata melhoras em 1-2 semanas de uso regular.',

    // WhatsApp
    'whatsapp.back': 'Voltar',
    'whatsapp.consultation.title': 'Consulta Especializada',
    'whatsapp.consultation.description': 'Atendimento personalizado para casos complexos',
    'whatsapp.features.specialized.title': 'Atendimento Especializado',
    'whatsapp.features.specialized.subtitle': 'Profissional qualificado',
    'whatsapp.features.specialized.professional': '15+ anos de experiência',
    'whatsapp.features.fast.title': 'Resposta Rápida',
    'whatsapp.features.fast.subtitle': 'Até 2 horas',
    'whatsapp.features.direct.title': 'WhatsApp Direto',
    'whatsapp.features.direct.subtitle': 'Comunicação direta',
    'whatsapp.when.title': 'Quando buscar ajuda:',
    'whatsapp.when.chronic': 'Dores crônicas persistentes',
    'whatsapp.when.neurological': 'Problemas neurológicos',
    'whatsapp.when.nonresponsive': 'Casos não responsivos',
    'whatsapp.when.personalized': 'Tratamento personalizado',
    'whatsapp.testimonial.text': 'Atendimento excepcional! Resolveu minha dor crônica em poucas sessões.',
    'whatsapp.testimonial.author': 'Maria S., São Paulo',
    'whatsapp.form.title': 'Formulário de Consulta',
    'whatsapp.form.subtitle': 'Preencha os dados para atendimento personalizado',
    'whatsapp.form.name': 'Nome Completo',
    'whatsapp.form.name.placeholder': 'Seu nome completo',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.email.placeholder': 'seu@email.com',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.whatsapp.placeholder': '(11) 99999-9999',
    'whatsapp.form.urgency': 'Urgência',
    'whatsapp.form.urgency.select': 'Selecione a urgência',
    'whatsapp.form.urgency.low': 'Baixa - Consulta de rotina',
    'whatsapp.form.urgency.medium': 'Média - Desconforto moderado',
    'whatsapp.form.urgency.high': 'Alta - Dor intensa',
    'whatsapp.form.urgency.urgent': 'Urgente - Necessita atenção imediata',
    'whatsapp.form.medical.title': 'Informações Médicas',
    'whatsapp.form.medical.condition': 'Condição Principal',
    'whatsapp.form.medical.condition.placeholder': 'Ex: Dor de cabeça crônica, ansiedade, insônia...',
    'whatsapp.form.medical.duration': 'Há quanto tempo tem os sintomas?',
    'whatsapp.form.medical.duration.placeholder': 'Ex: 2 meses, 1 ano...',
    'whatsapp.form.medical.symptoms': 'Descrição Detalhada dos Sintomas',
    'whatsapp.form.medical.symptoms.placeholder': 'Descreva em detalhes seus sintomas, quando ocorrem, intensidade...',
    'whatsapp.form.medical.treatments': 'Tratamentos Já Realizados',
    'whatsapp.form.medical.treatments.placeholder': 'Medicamentos, terapias, cirurgias...',
    'whatsapp.form.medical.medications': 'Medicamentos Atuais',
    'whatsapp.form.medical.medications.placeholder': 'Liste todos os medicamentos que usa atualmente...',
    'whatsapp.form.medical.schedule': 'Horário de Preferência',
    'whatsapp.form.medical.schedule.select': 'Selecione o melhor horário',
    'whatsapp.form.medical.schedule.morning': 'Manhã (8h-12h)',
    'whatsapp.form.medical.schedule.afternoon': 'Tarde (12h-18h)',
    'whatsapp.form.medical.schedule.evening': 'Noite (18h-22h)',
    'whatsapp.form.medical.schedule.anytime': 'Qualquer horário',
    'whatsapp.form.notice.title': 'Importante:',
    'whatsapp.form.notice.text': 'Este formulário será enviado diretamente para nosso especialista via WhatsApp.',
    'whatsapp.form.submit': 'Enviar para WhatsApp',
    'whatsapp.form.redirect': 'Você será redirecionado para o WhatsApp'
  },

  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.acupressure': 'Acupressure',
    'nav.breathing': 'Breathing',
    'nav.premium': 'Premium',
    'nav.corporate': 'Corporate',
    'nav.dashboard': 'Dashboard',
    'nav.sounds': 'Sounds',
    'nav.progress': 'Progress',
    'nav.personalization': 'Personalization',
    'nav.login': 'Login',
    'nav.logout': 'Logout',

    // Home
    'home.hero.title': 'Transform yourself',
    'home.hero.subtitle': 'Transmute with evidence-based integrative therapies',
    'home.hero.startNow': 'Start Now',
    'home.hero.createAccount': 'Create Account',
    'home.features.title': 'Complete Features',
    'home.features.subtitle': 'Everything you need for your wellness',
    'home.feature.acupressure.title': 'TCM Acupressure',
    'home.feature.acupressure.desc': '20 therapeutic points from Traditional Chinese Medicine',
    'home.feature.cranio.title': 'Craniopuncture',
    'home.feature.cranio.desc': 'Cranial techniques for memory, concentration and anxiety',
    'home.feature.breathing.title': '4-7-8 Breathing',
    'home.feature.breathing.desc': 'Scientific technique with timer and integrated chromotherapy',
    'home.feature.chromotherapy.title': 'Chromotherapy',
    'home.feature.chromotherapy.desc': 'Therapeutic colors based on neuroscience',
    'home.feature.sounds.title': 'Harmonizing Sounds',
    'home.feature.sounds.desc': 'Complete library + Spotify Premium integration',
    'home.feature.consultation.title': 'WhatsApp Consultations',
    'home.cta.title': 'Ready to start?',
    'home.cta.subtitle': 'Join thousands of people transforming their lives',
    'home.cta.demo': 'Try Free',
    'home.cta.corporate': 'Corporate Solutions',
    'home.compliance.title': 'Corporate Legal Compliance',
    'home.compliance.subtitle': 'Full compliance with Brazilian legislation',

    // Acupressure page
    'acupressure.title': 'Integrated Therapy',
    'acupressure.subtitle': 'Acupressure + 4-7-8 Breathing + Chromotherapy + Harmonizing Sounds',
    'acupressure.categories.all': 'All Points',
    'acupressure.categories.general': 'General TCM',
    'acupressure.categories.cranio': 'Craniopuncture',
    'acupressure.categories.septicemia': 'Septicemia',
    'acupressure.categories.atm': 'TMJ',
    'acupressure.point.benefits': 'What it\'s for',
    'acupressure.point.location': 'Location',
    'acupressure.point.instructions': 'How to apply',
    'acupressure.point.duration': 'Duration',
    'acupressure.point.pressure': 'Pressure',
    'acupressure.timer.active': 'Active Therapy',
    'acupressure.timer.start': 'Start Integrated Therapy',
    'acupressure.timer.stop': 'Stop',
    'acupressure.timer.reset': 'Reset',
    'acupressure.timer.switch': 'Switch to this Point',
    'acupressure.premium.unlock': 'Unlock Premium',
    'acupressure.premium.exclusive': 'Premium Point',
    'acupressure.select.title': 'Select a Point',
    'acupressure.select.subtitle': 'Click any point to start complete integrated therapy',
    'acupressure.integrated.description': 'Integrated Therapy: Precise timer acupressure, Synchronized 4-7-8 breathing, Vibrant chromotherapy, Optional harmonizing sounds',

    // Corporate page
    'corporate.hero.title': 'B2B Corporate Solutions',
    'corporate.hero.subtitle': 'Transform your company\'s wellness with technology and data',
    'corporate.benefits.title': 'Why choose XZenPress B2B?',
    'corporate.benefits.compliance': 'Legal Compliance',
    'corporate.benefits.compliance.desc': 'Full compliance with Law 14.831/2024 and NR-1',
    'corporate.benefits.roi': 'Proven ROI',
    'corporate.benefits.roi.desc': 'Return on investment in 6 months',
    'corporate.benefits.engagement': 'Engagement',
    'corporate.benefits.engagement.desc': '40% increase in employee wellness',
    'corporate.benefits.certification': 'Certification',
    'corporate.benefits.certification.desc': 'Mental Health Promoting Company Seal',
    'corporate.plans.title': 'Corporate Plans',
    'corporate.plans.subtitle': 'Complete wellness solutions for companies of all sizes',
    'corporate.analytics.title': 'B2B Analytics',
    'corporate.analytics.subtitle': 'Data intelligence to optimize corporate wellness',
    'corporate.roi.title': 'Proven ROI',
    'corporate.roi.subtitle': 'Companies that implemented XZenPress report:',
    'corporate.roi.stress': 'Stress reduction',
    'corporate.roi.absences': 'Fewer absences',
    'corporate.roi.engagement': 'Higher engagement',
    'corporate.roi.return': 'Return on investment',
    'corporate.contact.title': 'Ready to transform your company?',
    'corporate.contact.subtitle': 'Talk to our specialists and receive a personalized proposal',

    // Login
    'login.welcome': 'Welcome back',
    'login.createAccount': 'Create Account',
    'login.subtitle.login': 'Sign in to your account to continue',
    'login.subtitle.register': 'Create your account and start your journey',
    'login.name': 'Full Name',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.confirmPassword': 'Confirm Password',
    'login.forgotPassword': 'Forgot password',
    'login.noAccount': 'No account? Create one',
    'login.hasAccount': 'Already have account? Sign in',
    'login.demo.title': 'Demo',
    'login.demo.desc': 'Use any valid email + password with 6+ characters',
    'login.reset.title': 'Reset Password',
    'login.reset.subtitle': 'Enter your email to receive instructions',
    'login.reset.send': 'Send Email',
    'login.reset.back': 'Back to Login',

    // Breathing
    'breathing.title': '4-7-8 Breathing',
    'breathing.inhale': 'Inhale',
    'breathing.hold': 'Hold',
    'breathing.exhale': 'Exhale',
    'breathing.start': 'Start',
    'breathing.stop': 'Stop',
    'breathing.reset': 'Reset',
    'breathing.totalTime': 'Total Time',
    'breathing.phase': 'Phase',
    'breathing.phase.inhale.detail': 'Deep inhalation through nose',
    'breathing.phase.hold.detail': 'Hold air in lungs',
    'breathing.phase.exhale.detail': 'Slow exhalation through mouth',
    'breathing.chromotherapy.title': 'Scientific Chromotherapy',
    'breathing.chromotherapy.description': 'Therapeutic colors synchronized with each breathing phase',
    'breathing.chromotherapy.blue': 'Calming Blue',
    'breathing.chromotherapy.blue.desc': 'Reduces blood pressure and activates parasympathetic system',
    'breathing.chromotherapy.blue.short': 'Calming',
    'breathing.chromotherapy.green': 'Balancing Green',
    'breathing.chromotherapy.green.desc': 'Balances nervous system and harmonizes emotions',
    'breathing.chromotherapy.green.short': 'Balancing',
    'breathing.chromotherapy.magenta': 'Energizing Purple',
    'breathing.chromotherapy.magenta.desc': 'Stimulates endorphin production and releases tension',
    'breathing.chromotherapy.magenta.short': 'Energizing',
    'breathing.benefits.title': 'Scientific Benefits',
    'breathing.benefits.stress': 'Reduces cortisol',
    'breathing.benefits.sleep': 'Improves sleep',
    'breathing.benefits.focus': 'Increases focus',
    'breathing.benefits.pressure': 'Reduces pressure',
    'breathing.science.title': 'Scientific Foundation',
    'breathing.science.evidence': 'Scientific Evidence',
    'breathing.science.parasympathetic': 'Activates parasympathetic system',
    'breathing.science.cortisol': 'Reduces cortisol by 23%',
    'breathing.science.heartRate': 'Decreases heart rate',
    'breathing.science.gaba': 'Increases brain GABA',
    'breathing.science.chromotherapy': 'Chromotherapy',
    'breathing.science.blue.effect': 'Blue reduces blood pressure',
    'breathing.science.green.effect': 'Green balances nervous system',
    'breathing.science.magenta.effect': 'Purple stimulates endorphins',
    'breathing.science.melatonin': 'Colors regulate melatonin',
    'breathing.sounds.title': 'Harmonizing Sounds',
    'breathing.sounds.free.title': 'Free Sounds',
    'breathing.sounds.ocean': 'Ocean Sounds',
    'breathing.sounds.ocean.desc': 'Relaxing waves',
    'breathing.sounds.rain': 'Gentle Rain',
    'breathing.sounds.rain.desc': 'Calming rain',
    'breathing.sounds.forest': 'Forest',
    'breathing.sounds.fireplace': 'Fireplace',
    'breathing.sounds.classical': 'Classical',
    'breathing.sounds.mantras': 'Mantras',
    'breathing.sounds.more': '+45 sounds',
    'breathing.sounds.play': 'Play',
    'breathing.sounds.pause': 'Pause',
    'breathing.sounds.stop': 'Stop',
    'breathing.sounds.premium.title': 'Premium Library',
    'breathing.sounds.premium.desc': 'Over 50 exclusive sounds + Spotify integration',
    'breathing.sounds.premium.spotify': 'Open Spotify',
    'breathing.sounds.premium.upgrade': 'Upgrade Premium',

    // Premium
    'premium.hero.title': 'Unlock Full Potential',
    'premium.hero.subtitle': 'Complete access to specialized consultations and exclusive points',
    'premium.hero.active': 'Premium Active',
    'premium.hero.upgrade': 'Upgrade',
    'premium.features.title': 'Premium Features',
    'premium.features.available': 'Available',
    'premium.features.coming': 'Coming Soon',
    'premium.features.whatsapp.title': 'WhatsApp Consultations',
    'premium.features.whatsapp.description': 'Specialized care via WhatsApp',
    'premium.features.whatsapp.benefit1': 'Professional with 15+ years',
    'premium.features.whatsapp.benefit2': 'Response within 2h',
    'premium.features.whatsapp.benefit3': 'Complex cases',
    'premium.features.whatsapp.benefit4': 'Personalized follow-up',
    'premium.features.points.title': 'Exclusive Points',
    'premium.features.points.description': '11 specialized premium points',
    'premium.features.points.benefit1': 'Septicemia (3 points)',
    'premium.features.points.benefit2': 'TMJ (3 points)',
    'premium.features.points.benefit3': 'Craniotherapy (3 points)',
    'premium.features.points.benefit4': 'Neurology (2 points)',
    'premium.features.chromotherapy.title': 'Advanced Chromotherapy',
    'premium.features.chromotherapy.description': 'Personalized color sequences',
    'premium.features.chromotherapy.benefit1': 'Adaptive profiles',
    'premium.features.chromotherapy.benefit2': 'Biofeedback sync',
    'premium.features.chromotherapy.benefit3': 'Custom colors',
    'premium.features.chromotherapy.benefit4': 'Integrated therapy',
    'premium.features.sounds.title': 'Complete Library',
    'premium.features.sounds.description': '50+ sounds + Spotify Premium',
    'premium.features.sounds.benefit1': 'Binaural frequencies',
    'premium.features.sounds.benefit2': 'Sacred mantras',
    'premium.features.sounds.benefit3': 'Nature HD',
    'premium.features.sounds.benefit4': 'Curated playlists',
    'premium.features.ai.title': 'AI Recommendations',
    'premium.features.ai.description': 'Personalized artificial intelligence',
    'premium.features.ai.benefit1': 'Pattern analysis',
    'premium.features.ai.benefit2': 'Personalized suggestions',
    'premium.features.ai.benefit3': 'Automatic optimization',
    'premium.features.ai.benefit4': 'Predictive insights',
    'premium.features.offline.title': 'Offline Mode',
    'premium.features.offline.description': 'Complete offline functionality',
    'premium.features.offline.benefit1': 'Automatic sync',
    'premium.features.offline.benefit2': 'Smart cache',
    'premium.features.offline.benefit3': 'Secure data',
    'premium.features.offline.benefit4': 'No internet access',
    'premium.plans.title': 'Premium Plans',
    'premium.plans.subtitle': 'Choose the ideal plan for you',
    'premium.plans.popular': 'Most Popular',
    'premium.plans.choose': 'Choose Plan',
    'premium.plans.save': 'Save',
    'premium.plans.monthly.name': 'Monthly Premium',
    'premium.plans.monthly.period': '/month',
    'premium.plans.monthly.feature1': 'Unlimited WhatsApp consultations',
    'premium.plans.monthly.feature2': '11 exclusive points',
    'premium.plans.monthly.feature3': 'Complete sound library',
    'premium.plans.monthly.feature4': 'Advanced chromotherapy',
    'premium.plans.monthly.feature5': 'Priority support',
    'premium.plans.annual.name': 'Annual Premium',
    'premium.plans.annual.period': '/year',
    'premium.plans.annual.feature1': 'Everything from monthly plan',
    'premium.plans.annual.feature2': '2 months free',
    'premium.plans.annual.feature3': 'AI recommendations',
    'premium.plans.annual.feature4': 'Advanced reports',
    'premium.plans.annual.feature5': 'Beta access to new features',
    'premium.plans.lifetime.name': 'Lifetime Premium',
    'premium.plans.lifetime.period': 'one-time payment',
    'premium.plans.lifetime.feature1': 'Complete lifetime access',
    'premium.plans.lifetime.feature2': 'All future features',
    'premium.plans.lifetime.feature3': 'VIP support',
    'premium.plans.lifetime.feature4': 'Personalized consulting',
    'premium.plans.lifetime.feature5': 'No monthly fees',
    'premium.payment.title': 'Complete Payment',
    'premium.payment.methods': 'Payment Methods',
    'premium.payment.pix': 'PIX',
    'premium.payment.pix.desc': 'Instant',
    'premium.payment.pix.title': 'PIX Payment',
    'premium.payment.credit': 'Card',
    'premium.payment.credit.desc': 'Visa, Master, Amex',
    'premium.payment.credit.title': 'Credit Card',
    'premium.payment.crypto': 'Crypto',
    'premium.payment.crypto.desc': 'Bitcoin, Ethereum',
    'premium.payment.crypto.title': 'Cryptocurrencies',
    'premium.payment.back': 'Back',
    'premium.payment.confirm': 'Confirm Payment',
    'premium.testimonials.title': 'Testimonials',
    'premium.testimonials.maria': 'Exceptional service! Solved my chronic pain in just a few sessions.',
    'premium.testimonials.joao': 'The platform changed my life. I sleep better and have less anxiety.',
    'premium.testimonials.ana': 'Very competent professional. I recommend it to everyone!',
    'premium.faq.title': 'Frequently Asked Questions',
    'premium.faq.q1': 'How does WhatsApp service work?',
    'premium.faq.a1': 'You fill out a detailed form and receive personalized care via WhatsApp.',
    'premium.faq.q2': 'Can I cancel anytime?',
    'premium.faq.a2': 'Yes, you can cancel your subscription anytime without fees.',
    'premium.faq.q3': 'Are premium points safe?',
    'premium.faq.a3': 'All points are based on Traditional Chinese Medicine with professional supervision.',
    'premium.faq.q4': 'How long to see results?',
    'premium.faq.a4': 'Most users report improvements within 1-2 weeks of regular use.',

    // WhatsApp
    'whatsapp.back': 'Back',
    'whatsapp.consultation.title': 'Specialized Consultation',
    'whatsapp.consultation.description': 'Personalized care for complex cases',
    'whatsapp.features.specialized.title': 'Specialized Care',
    'whatsapp.features.specialized.subtitle': 'Qualified professional',
    'whatsapp.features.specialized.professional': '15+ years experience',
    'whatsapp.features.fast.title': 'Fast Response',
    'whatsapp.features.fast.subtitle': 'Within 2 hours',
    'whatsapp.features.direct.title': 'Direct WhatsApp',
    'whatsapp.features.direct.subtitle': 'Direct communication',
    'whatsapp.when.title': 'When to seek help:',
    'whatsapp.when.chronic': 'Persistent chronic pain',
    'whatsapp.when.neurological': 'Neurological problems',
    'whatsapp.when.nonresponsive': 'Non-responsive cases',
    'whatsapp.when.personalized': 'Personalized treatment',
    'whatsapp.testimonial.text': 'Exceptional service! Solved my chronic pain in just a few sessions.',
    'whatsapp.testimonial.author': 'Maria S., São Paulo',
    'whatsapp.form.title': 'Consultation Form',
    'whatsapp.form.subtitle': 'Fill in the details for personalized care',
    'whatsapp.form.name': 'Full Name',
    'whatsapp.form.name.placeholder': 'Your full name',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.email.placeholder': 'your@email.com',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.whatsapp.placeholder': '+1 (555) 123-4567',
    'whatsapp.form.urgency': 'Urgency',
    'whatsapp.form.urgency.select': 'Select urgency',
    'whatsapp.form.urgency.low': 'Low - Routine consultation',
    'whatsapp.form.urgency.medium': 'Medium - Moderate discomfort',
    'whatsapp.form.urgency.high': 'High - Intense pain',
    'whatsapp.form.urgency.urgent': 'Urgent - Needs immediate attention',
    'whatsapp.form.medical.title': 'Medical Information',
    'whatsapp.form.medical.condition': 'Main Condition',
    'whatsapp.form.medical.condition.placeholder': 'Ex: Chronic headache, anxiety, insomnia...',
    'whatsapp.form.medical.duration': 'How long have you had symptoms?',
    'whatsapp.form.medical.duration.placeholder': 'Ex: 2 months, 1 year...',
    'whatsapp.form.medical.symptoms': 'Detailed Symptom Description',
    'whatsapp.form.medical.symptoms.placeholder': 'Describe your symptoms in detail, when they occur, intensity...',
    'whatsapp.form.medical.treatments': 'Previous Treatments',
    'whatsapp.form.medical.treatments.placeholder': 'Medications, therapies, surgeries...',
    'whatsapp.form.medical.medications': 'Current Medications',
    'whatsapp.form.medical.medications.placeholder': 'List all medications you currently use...',
    'whatsapp.form.medical.schedule': 'Preferred Time',
    'whatsapp.form.medical.schedule.select': 'Select best time',
    'whatsapp.form.medical.schedule.morning': 'Morning (8am-12pm)',
    'whatsapp.form.medical.schedule.afternoon': 'Afternoon (12pm-6pm)',
    'whatsapp.form.medical.schedule.evening': 'Evening (6pm-10pm)',
    'whatsapp.form.medical.schedule.anytime': 'Anytime',
    'whatsapp.form.notice.title': 'Important:',
    'whatsapp.form.notice.text': 'This form will be sent directly to our specialist via WhatsApp.',
    'whatsapp.form.submit': 'Send to WhatsApp',
    'whatsapp.form.redirect': 'You will be redirected to WhatsApp'
  },

  es: {
    // Navegación
    'nav.home': 'Inicio',
    'nav.acupressure': 'Acupresión',
    'nav.breathing': 'Respiración',
    'nav.premium': 'Premium',
    'nav.corporate': 'Corporativo',
    'nav.dashboard': 'Panel',
    'nav.sounds': 'Sonidos',
    'nav.progress': 'Progreso',
    'nav.personalization': 'Personalización',
    'nav.login': 'Entrar',
    'nav.logout': 'Salir',

    // Inicio
    'home.hero.title': 'Transforma tu vida con terapias integrativas',
    'home.hero.subtitle': 'Transmutar tu vida con terapias basadas en evidencia científica',
    'home.hero.startNow': 'Comenzar Ahora',
    'home.hero.createAccount': 'Crear Cuenta',
    'home.features.title': 'Características Completas',
    'home.features.subtitle': 'Todo lo que necesitas para tu bienestar',
    'home.feature.acupressure.title': 'Acupresión MTC',
    'home.feature.acupressure.desc': '20 puntos terapéuticos de Medicina Tradicional China',
    'home.feature.cranio.title': 'Craniopuntura',
    'home.feature.cranio.desc': 'Técnicas craneales para memoria, concentración y ansiedad',
    'home.feature.breathing.title': 'Respiración 4-7-8',
    'home.feature.breathing.desc': 'Técnica científica con temporizador y cromoterapia integrada',
    'home.feature.chromotherapy.title': 'Cromoterapia',
    'home.feature.chromotherapy.desc': 'Colores terapéuticos basados en neurociencia',
    'home.feature.sounds.title': 'Sonidos Armonizantes',
    'home.feature.sounds.desc': 'Biblioteca completa + integración Spotify Premium',
    'home.feature.consultation.title': 'Consultas WhatsApp',
    'home.cta.title': '¿Listo para comenzar?',
    'home.cta.subtitle': 'Únete a miles de personas transformando sus vidas',
    'home.cta.demo': 'Probar Gratis',
    'home.cta.corporate': 'Soluciones Corporativas',
    'home.compliance.title': 'Cumplimiento Legal Corporativo',
    'home.compliance.subtitle': 'Cumplimiento integral con legislación brasileña',

    // Acupressure page
    'acupressure.title': 'Terapia Integrada',
    'acupressure.subtitle': 'Acupresión + Respiración 4-7-8 + Cromoterapia + Sonidos Armonizantes',
    'acupressure.categories.all': 'Todos los Puntos',
    'acupressure.categories.general': 'MTC General',
    'acupressure.categories.cranio': 'Craniopuntura',
    'acupressure.categories.septicemia': 'Septicemia',
    'acupressure.categories.atm': 'ATM',
    'acupressure.point.benefits': 'Para qué sirve',
    'acupressure.point.location': 'Ubicación',
    'acupressure.point.instructions': 'Cómo aplicar',
    'acupressure.point.duration': 'Duración',
    'acupressure.point.pressure': 'Presión',
    'acupressure.timer.active': 'Terapia Activa',
    'acupressure.timer.start': 'Iniciar Terapia Integrada',
    'acupressure.timer.stop': 'Parar',
    'acupressure.timer.reset': 'Reiniciar',
    'acupressure.timer.switch': 'Cambiar a este Punto',
    'acupressure.premium.unlock': 'Desbloquear Premium',
    'acupressure.premium.exclusive': 'Punto Premium',
    'acupressure.select.title': 'Selecciona un Punto',
    'acupressure.select.subtitle': 'Haz clic en cualquier punto para iniciar terapia integrada completa',
    'acupressure.integrated.description': 'Terapia Integrada: Acupresión con temporizador preciso, Respiración 4-7-8 sincronizada, Cromoterapia vibrante, Sonidos armonizantes opcionales',

    // Corporate page
    'corporate.hero.title': 'Soluciones Corporativas B2B',
    'corporate.hero.subtitle': 'Transforma el bienestar de tu empresa con tecnología y datos',
    'corporate.benefits.title': '¿Por qué elegir XZenPress B2B?',
    'corporate.benefits.compliance': 'Cumplimiento Legal',
    'corporate.benefits.compliance.desc': 'Cumplimiento integral con Ley 14.831/2024 y NR-1',
    'corporate.benefits.roi': 'ROI Comprobado',
    'corporate.benefits.roi.desc': 'Retorno de inversión en 6 meses',
    'corporate.benefits.engagement': 'Compromiso',
    'corporate.benefits.engagement.desc': '40% de aumento en bienestar de empleados',
    'corporate.benefits.certification': 'Certificación',
    'corporate.benefits.certification.desc': 'Sello de Empresa Promotora de Salud Mental',
    'corporate.plans.title': 'Planes Corporativos',
    'corporate.plans.subtitle': 'Soluciones completas de bienestar para empresas de todos los tamaños',
    'corporate.analytics.title': 'Analytics B2B',
    'corporate.analytics.subtitle': 'Inteligencia de datos para optimizar bienestar corporativo',
    'corporate.roi.title': 'ROI Comprobado',
    'corporate.roi.subtitle': 'Empresas que implementaron XZenPress reportan:',
    'corporate.roi.stress': 'Reducción del estrés',
    'corporate.roi.absences': 'Menos ausencias',
    'corporate.roi.engagement': 'Mayor compromiso',
    'corporate.roi.return': 'Retorno de inversión',
    'corporate.contact.title': '¿Listo para transformar tu empresa?',
    'corporate.contact.subtitle': 'Habla con nuestros especialistas y recibe una propuesta personalizada'
  },

  zh: {
    // 导航
    'nav.home': '首页',
    'nav.acupressure': '穴位按摩',
    'nav.breathing': '呼吸',
    'nav.premium': '高级版',
    'nav.corporate': '企业版',
    'nav.dashboard': '仪表板',
    'nav.sounds': '声音',
    'nav.progress': '进度',
    'nav.personalization': '个性化',
    'nav.login': '登录',
    'nav.logout': '退出',

    // 首页
    'home.hero.title': '用整体疗法改变你的生活',
    'home.hero.subtitle': '用基于科学证据的整体疗法改变您的生活',
    'home.hero.startNow': '立即开始',
    'home.hero.createAccount': '创建账户',
    'home.features.title': '完整功能',
    'home.features.subtitle': '您健康所需的一切',
    'home.feature.acupressure.title': '中医穴位按摩',
    'home.feature.acupressure.desc': '20个传统中医治疗穴位',
    'home.feature.cranio.title': '头针疗法',
    'home.feature.cranio.desc': '针对记忆、专注力和焦虑的头部技术',
    'home.feature.breathing.title': '4-7-8呼吸法',
    'home.feature.breathing.desc': '科学技术配合计时器和综合色彩疗法',
    'home.feature.chromotherapy.title': '色彩疗法',
    'home.feature.chromotherapy.desc': '基于神经科学的治疗色彩',
    'home.feature.sounds.title': '和谐音效',
    'home.feature.sounds.desc': '完整音库 + Spotify Premium集成',
    'home.feature.consultation.title': 'WhatsApp咨询',
    'home.cta.title': '准备开始了吗？',
    'home.cta.subtitle': '加入数千人改变生活的行列',
    'home.cta.demo': '免费试用',
    'home.cta.corporate': '企业解决方案',
    'home.compliance.title': '企业法律合规',
    'home.compliance.subtitle': '全面符合巴西法律',

    // Acupressure page
    'acupressure.title': '综合疗法',
    'acupressure.subtitle': '穴位按摩 + 4-7-8呼吸法 + 色彩疗法 + 和谐声音',
    'acupressure.categories.all': '所有穴位',
    'acupressure.categories.general': '中医一般',
    'acupressure.categories.cranio': '颅针疗法',
    'acupressure.categories.septicemia': '败血症',
    'acupressure.categories.atm': '颞下颌关节',
    'acupressure.point.benefits': '作用',
    'acupressure.point.location': '位置',
    'acupressure.point.instructions': '如何应用',
    'acupressure.point.duration': '持续时间',
    'acupressure.point.pressure': '压力',
    'acupressure.timer.active': '活跃疗法',
    'acupressure.timer.start': '开始综合疗法',
    'acupressure.timer.stop': '停止',
    'acupressure.timer.reset': '重置',
    'acupressure.timer.switch': '切换到此穴位',
    'acupressure.premium.unlock': '解锁高级版',
    'acupressure.premium.exclusive': '高级穴位',
    'acupressure.select.title': '选择一个穴位',
    'acupressure.select.subtitle': '点击任何穴位开始完整的综合疗法',
    'acupressure.integrated.description': '综合疗法：精确计时器穴位按摩，同步4-7-8呼吸，鲜艳色彩疗法，可选和谐声音',

    // Corporate page
    'corporate.hero.title': 'B2B企业解决方案',
    'corporate.hero.subtitle': '用技术和数据改变您公司的健康',
    'corporate.benefits.title': '为什么选择XZenPress B2B？',
    'corporate.benefits.compliance': '法律合规',
    'corporate.benefits.compliance.desc': '完全符合法律14.831/2024和NR-1',
    'corporate.benefits.roi': '经证实的投资回报率',
    'corporate.benefits.roi.desc': '6个月内投资回报',
    'corporate.benefits.engagement': '参与度',
    'corporate.benefits.engagement.desc': '员工健康提高40%',
    'corporate.benefits.certification': '认证',
    'corporate.benefits.certification.desc': '心理健康促进公司印章',
    'corporate.plans.title': '企业计划',
    'corporate.plans.subtitle': '适合各种规模企业的完整健康解决方案',
    'corporate.analytics.title': 'B2B分析',
    'corporate.analytics.subtitle': '优化企业健康的数据智能',
    'corporate.roi.title': '经证实的投资回报率',
    'corporate.roi.subtitle': '实施XZenPress的公司报告：',
    'corporate.roi.stress': '压力减少',
    'corporate.roi.absences': '缺勤减少',
    'corporate.roi.engagement': '更高参与度',
    'corporate.roi.return': '投资回报',
    'corporate.contact.title': '准备改变您的公司吗？',
    'corporate.contact.subtitle': '与我们的专家交谈并获得个性化提案'
  },

  hi: {
    // नेवीगेशन
    'nav.home': 'होम',
    'nav.acupressure': 'एक्यूप्रेशर',
    'nav.breathing': 'श्वास',
    'nav.premium': 'प्रीमियम',
    'nav.corporate': 'कॉर्पोरेट',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.sounds': 'ध्वनि',
    'nav.progress': 'प्रगति',
    'nav.personalization': 'व्यक्तिगतकरण',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉगआउट',

    // होम
    'home.hero.title': 'समग्र चिकित्सा से अपना जीवन बदलें',
    'home.hero.subtitle': 'वैज्ञानिक प्रमाणों पर आधारित समग्र चिकित्सा से अपना जीवन बदलें',
    'home.hero.startNow': 'अभी शुरू करें',
    'home.hero.createAccount': 'खाता बनाएं',
    'home.features.title': 'पूर्ण सुविधाएं',
    'home.features.subtitle': 'आपकी भलाई के लिए आवश्यक सब कुछ',
    'home.feature.acupressure.title': 'TCM एक्यूप्रेशर',
    'home.feature.acupressure.desc': 'पारंपरिक चीनी चिकित्सा के 20 चिकित्सीय बिंदु',
    'home.feature.cranio.title': 'क्रेनियोपंक्चर',
    'home.feature.cranio.desc': 'स्मृति, एकाग्रता और चिंता के लिए कपाल तकनीक',
    'home.feature.breathing.title': '4-7-8 श्वास',
    'home.feature.breathing.desc': 'टाइमर और एकीकृत रंग चिकित्सा के साथ वैज्ञानिक तकनीक',
    'home.feature.chromotherapy.title': 'रंग चिकित्सा',
    'home.feature.chromotherapy.desc': 'न्यूरोसाइंस पर आधारित चिकित्सीय रंग',
    'home.feature.sounds.title': 'सामंजस्यपूर्ण ध्वनियां',
    'home.feature.sounds.desc': 'पूर्ण लाइब्रेरी + Spotify Premium एकीकरण',
    'home.feature.consultation.title': 'WhatsApp परामर्श',
    'home.cta.title': 'शुरू करने के लिए तैयार?',
    'home.cta.subtitle': 'हजारों लोगों के साथ जुड़ें जो अपना जीवन बदल रहे हैं',
    'home.cta.demo': 'मुफ्त आज़माएं',
    'home.cta.corporate': 'कॉर्पोरेट समाधान',
    'home.compliance.title': 'कॉर्पोरेट कानूनी अनुपालन',
    'home.compliance.subtitle': 'ब्राजीलियाई कानून के साथ पूर्ण अनुपालन',

    // Acupressure page
    'acupressure.title': 'एकीकृत चिकित्सा',
    'acupressure.subtitle': 'एक्यूप्रेशर + 4-7-8 श्वास + रंग चिकित्सा + सामंजस्यपूर्ण ध्वनियां',
    'acupressure.categories.all': 'सभी बिंदु',
    'acupressure.categories.general': 'सामान्य TCM',
    'acupressure.categories.cranio': 'क्रेनियोपंक्चर',
    'acupressure.categories.septicemia': 'सेप्टिसीमिया',
    'acupressure.categories.atm': 'TMJ',
    'acupressure.point.benefits': 'इसका उपयोग',
    'acupressure.point.location': 'स्थान',
    'acupressure.point.instructions': 'कैसे लगाएं',
    'acupressure.point.duration': 'अवधि',
    'acupressure.point.pressure': 'दबाव',
    'acupressure.timer.active': 'सक्रिय चिकित्सा',
    'acupressure.timer.start': 'एकीकृत चिकित्सा शुरू करें',
    'acupressure.timer.stop': 'रोकें',
    'acupressure.timer.reset': 'रीसेट करें',
    'acupressure.timer.switch': 'इस बिंदु पर स्विच करें',
    'acupressure.premium.unlock': 'प्रीमियम अनलॉक करें',
    'acupressure.premium.exclusive': 'प्रीमियम बिंदु',
    'acupressure.select.title': 'एक बिंदु चुनें',
    'acupressure.select.subtitle': 'पूर्ण एकीकृत चिकित्सा शुरू करने के लिए किसी भी बिंदु पर क्लिक करें',
    'acupressure.integrated.description': 'एकीकृत चिकित्सा: सटीक टाइमर एक्यूप्रेशर, सिंक्रोनाइज़्ड 4-7-8 श्वास, जीवंत रंग चिकित्सा, वैकल्पिक सामंजस्यपूर्ण ध्वनियां',

    // Corporate page
    'corporate.hero.title': 'B2B कॉर्पोरेट समाधान',
    'corporate.hero.subtitle': 'प्रौद्योगिकी और डेटा के साथ अपनी कंपनी की भलाई को बदलें',
    'corporate.benefits.title': 'XZenPress B2B क्यों चुनें?',
    'corporate.benefits.compliance': 'कानूनी अनुपालन',
    'corporate.benefits.compliance.desc': 'कानून 14.831/2024 और NR-1 के साथ पूर्ण अनुपालन',
    'corporate.benefits.roi': 'सिद्ध ROI',
    'corporate.benefits.roi.desc': '6 महीने में निवेश पर रिटर्न',
    'corporate.benefits.engagement': 'सहभागिता',
    'corporate.benefits.engagement.desc': 'कर्मचारी कल्याण में 40% वृद्धि',
    'corporate.benefits.certification': 'प्रमाणन',
    'corporate.benefits.certification.desc': 'मानसिक स्वास्थ्य प्रोत्साहन कंपनी मुहर',
    'corporate.plans.title': 'कॉर्पोरेट योजनाएं',
    'corporate.plans.subtitle': 'सभी आकार की कंपनियों के लिए पूर्ण कल्याण समाधान',
    'corporate.analytics.title': 'B2B एनालिटिक्स',
    'corporate.analytics.subtitle': 'कॉर्पोरेट कल्याण को अनुकूलित करने के लिए डेटा बुद्धिमत्ता',
    'corporate.roi.title': 'सिद्ध ROI',
    'corporate.roi.subtitle': 'XZenPress लागू करने वाली कंपनियां रिपोर्ट करती हैं:',
    'corporate.roi.stress': 'तनाव में कमी',
    'corporate.roi.absences': 'कम अनुपस्थिति',
    'corporate.roi.engagement': 'उच्च सहभागिता',
    'corporate.roi.return': 'निवेश पर रिटर्न',
    'corporate.contact.title': 'अपनी कंपनी को बदलने के लिए तैयार?',
    'corporate.contact.subtitle': 'हमारे विशेषज्ञों से बात करें और व्यक्तिगत प्रस्ताव प्राप्त करें'
  },

  ar: {
    // التنقل
    'nav.home': 'الرئيسية',
    'nav.acupressure': 'العلاج بالضغط',
    'nav.breathing': 'التنفس',
    'nav.premium': 'المميز',
    'nav.corporate': 'الشركات',
    'nav.dashboard': 'لوحة التحكم',
    'nav.sounds': 'الأصوات',
    'nav.progress': 'التقدم',
    'nav.personalization': 'التخصيص',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',

    // الرئيسية
    'home.hero.title': 'حول حياتك بالعلاجات الشاملة',
    'home.hero.subtitle': 'حول حياتك بالعلاجات الشاملة المبنية على الأدلة العلمية',
    'home.hero.startNow': 'ابدأ الآن',
    'home.hero.createAccount': 'إنشاء حساب',
    'home.features.title': 'ميزات كاملة',
    'home.features.subtitle': 'كل ما تحتاجه لصحتك',
    'home.feature.acupressure.title': 'العلاج بالضغط الصيني',
    'home.feature.acupressure.desc': '20 نقطة علاجية من الطب الصيني التقليدي',
    'home.feature.cranio.title': 'العلاج القحفي',
    'home.feature.cranio.desc': 'تقنيات الجمجمة للذاكرة والتركيز والقلق',
    'home.feature.breathing.title': 'تنفس 4-7-8',
    'home.feature.breathing.desc': 'تقنية علمية مع مؤقت وعلاج بالألوان متكامل',
    'home.feature.chromotherapy.title': 'العلاج بالألوان',
    'home.feature.chromotherapy.desc': 'ألوان علاجية مبنية على علم الأعصاب',
    'home.feature.sounds.title': 'أصوات متناغمة',
    'home.feature.sounds.desc': 'مكتبة كاملة + تكامل Spotify Premium',
    'home.feature.consultation.title': 'استشارات WhatsApp',
    'home.cta.title': 'مستعد للبدء؟',
    'home.cta.subtitle': 'انضم لآلاف الأشخاص الذين يحولون حياتهم',
    'home.cta.demo': 'جرب مجاناً',
    'home.cta.corporate': 'حلول الشركات',
    'home.compliance.title': 'الامتثال القانوني للشركات',
    'home.compliance.subtitle': 'امتثال كامل للتشريع البرازيلي',

    // Acupressure page
    'acupressure.title': 'العلاج المتكامل',
    'acupressure.subtitle': 'العلاج بالضغط + تنفس 4-7-8 + العلاج بالألوان + أصوات متناغمة',
    'acupressure.categories.all': 'جميع النقاط',
    'acupressure.categories.general': 'TCM عام',
    'acupressure.categories.cranio': 'الوخز القحفي',
    'acupressure.categories.septicemia': 'تسمم الدم',
    'acupressure.categories.atm': 'TMJ',
    'acupressure.point.benefits': 'الغرض منه',
    'acupressure.point.location': 'الموقع',
    'acupressure.point.instructions': 'كيفية التطبيق',
    'acupressure.point.duration': 'المدة',
    'acupressure.point.pressure': 'الضغط',
    'acupressure.timer.active': 'العلاج النشط',
    'acupressure.timer.start': 'بدء العلاج المتكامل',
    'acupressure.timer.stop': 'توقف',
    'acupressure.timer.reset': 'إعادة تعيين',
    'acupressure.timer.switch': 'التبديل إلى هذه النقطة',
    'acupressure.premium.unlock': 'فتح المميز',
    'acupressure.premium.exclusive': 'نقطة مميزة',
    'acupressure.select.title': 'اختر نقطة',
    'acupressure.select.subtitle': 'انقر على أي نقطة لبدء العلاج المتكامل الكامل',
    'acupressure.integrated.description': 'العلاج المتكامل: العلاج بالضغط بمؤقت دقيق، تنفس 4-7-8 متزامن، علاج بالألوان نابض بالحياة، أصوات متناغمة اختيارية',

    // Corporate page
    'corporate.hero.title': 'حلول الشركات B2B',
    'corporate.hero.subtitle': 'حول عافية شركتك بالتكنولوجيا والبيانات',
    'corporate.benefits.title': 'لماذا تختار XZenPress B2B؟',
    'corporate.benefits.compliance': 'الامتثال القانوني',
    'corporate.benefits.compliance.desc': 'امتثال كامل للقانون 14.831/2024 و NR-1',
    'corporate.benefits.roi': 'عائد استثمار مثبت',
    'corporate.benefits.roi.desc': 'عائد على الاستثمار في 6 أشهر',
    'corporate.benefits.engagement': 'المشاركة',
    'corporate.benefits.engagement.desc': 'زيادة 40% في عافية الموظفين',
    'corporate.benefits.certification': 'الشهادة',
    'corporate.benefits.certification.desc': 'ختم شركة تعزيز الصحة النفسية',
    'corporate.plans.title': 'الخطط الشركات',
    'corporate.plans.subtitle': 'حلول عافية كاملة للشركات من جميع الأحجام',
    'corporate.analytics.title': 'تحليلات B2B',
    'corporate.analytics.subtitle': 'ذكاء البيانات لتحسين العافية الشركات',
    'corporate.roi.title': 'عائد استثمار مثبت',
    'corporate.roi.subtitle': 'الشركات التي نفذت XZenPress تقرر:',
    'corporate.roi.stress': 'تقليل التوتر',
    'corporate.roi.absences': 'غيابات أقل',
    'corporate.roi.engagement': 'مشاركة أعلى',
    'corporate.roi.return': 'عائد الاستثمار',
    'corporate.contact.title': 'مستعد لتحويل شركتك؟',
    'corporate.contact.subtitle': 'تحدث مع متخصصينا واحصل على اقتراح شخصي'
  },

  bn: {
    // নেভিগেশন
    'nav.home': 'হোম',
    'nav.acupressure': 'আকুপ্রেশার',
    'nav.breathing': 'শ্বাস',
    'nav.premium': 'প্রিমিয়াম',
    'nav.corporate': 'কর্পোরেট',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.sounds': 'শব্দ',
    'nav.progress': 'অগ্রগতি',
    'nav.personalization': 'ব্যক্তিগতকরণ',
    'nav.login': 'লগইন',
    'nav.logout': 'লগআউট',

    // হোম
    'home.hero.title': 'সামগ্রিক থেরাপি দিয়ে আপনার জীবন পরিবর্তন করুন',
    'home.hero.subtitle': 'বৈজ্ঞানিক প্রমাণের উপর ভিত্তি করে সামগ্রিক চিকিৎসা দিয়ে আপনার জীবন পরিবর্তন করুন',
    'home.hero.startNow': 'এখনই শুরু করুন',
    'home.hero.createAccount': 'অ্যাকাউন্ট তৈরি করুন',
    'home.features.title': 'সম্পূর্ণ বৈশিষ্ট্য',
    'home.features.subtitle': 'আপনার সুস্থতার জন্য প্রয়োজনীয় সবকিছু',
    'home.feature.acupressure.title': 'TCM আকুপ্রেশার',
    'home.feature.acupressure.desc': 'ঐতিহ্যবাহী চীনা চিকিৎসার 20টি থেরাপিউটিক পয়েন্ট',
    'home.feature.cranio.title': 'ক্রেনিওপাংচার',
    'home.feature.cranio.desc': 'স্মৃতি, একাগ্রতা এবং উদ্বেগের জন্য মাথার কৌশল',
    'home.feature.breathing.title': '4-7-8 শ্বাস',
    'home.feature.breathing.desc': 'টাইমার এবং সমন্বিত রঙ থেরাপি সহ বৈজ্ঞানিক কৌশল',
    'home.feature.chromotherapy.title': 'রঙ থেরাপি',
    'home.feature.chromotherapy.desc': 'নিউরোসায়েন্স ভিত্তিক থেরাপিউটিক রঙ',
    'home.feature.sounds.title': 'সুরেলা শব্দ',
    'home.feature.sounds.desc': 'সম্পূর্ণ লাইব্রেরি + Spotify Premium ইন্টিগ্রেশন',
    'home.feature.consultation.title': 'WhatsApp পরামর্শ',
    'home.cta.title': 'শুরু করতে প্রস্তুত?',
    'home.cta.subtitle': 'হাজার হাজার মানুষের সাথে যোগ দিন যারা তাদের জীবন পরিবর্তন করছে',
    'home.cta.demo': 'বিনামূল্যে চেষ্টা করুন',
    'home.cta.corporate': 'কর্পোরেট সমাধান',
    'home.compliance.title': 'কর্পোরেট আইনি সম্মতি',
    'home.compliance.subtitle': 'ব্রাজিলীয় আইনের সাথে সম্পূর্ণ সম্মতি',

    // Acupressure page
    'acupressure.title': 'সমন্বিত চিকিৎসা',
    'acupressure.subtitle': 'অ্যাকুপ্রেশার + ৪-৭-৮ শ্বাস + রঙ চিকিৎসা + সুরেলা শব্দ',
    'acupressure.categories.all': 'সব পয়েন্ট',
    'acupressure.categories.general': 'সাধারণ TCM',
    'acupressure.categories.cranio': 'ক্রানিওপাংচার',
    'acupressure.categories.septicemia': 'সেপটিসেমিয়া',
    'acupressure.categories.atm': 'TMJ',
    'acupressure.point.benefits': 'কিসের জন্য',
    'acupressure.point.location': 'অবস্থান',
    'acupressure.point.instructions': 'কীভাবে প্রয়োগ করবেন',
    'acupressure.point.duration': 'সময়কাল',
    'acupressure.point.pressure': 'চাপ',
    'acupressure.timer.active': 'সক্রিয় চিকিৎসা',
    'acupressure.timer.start': 'সমন্বিত চিকিৎসা শুরু করুন',
    'acupressure.timer.stop': 'থামান',
    'acupressure.timer.reset': 'রিসেট করুন',
    'acupressure.timer.switch': 'এই পয়েন্টে স্যুইচ করুন',
    'acupressure.premium.unlock': 'প্রিমিয়াম আনলক করুন',
    'acupressure.premium.exclusive': 'প্রিমিয়াম পয়েন্ট',
    'acupressure.select.title': 'একটি পয়েন্ট নির্বাচন করুন',
    'acupressure.select.subtitle': 'সম্পূর্ণ সমন্বিত চিকিৎসা শুরু করতে যেকোনো পয়েন্টে ক্লিক করুন',
    'acupressure.integrated.description': 'সমন্বিত চিকিৎসা: নির্ভুল টাইমার অ্যাকুপ্রেশার, সিঙ্ক্রোনাইজড ৪-৭-৮ শ্বাস, প্রাণবন্ত রঙ চিকিৎসা, ঐচ্ছিক সুরেলা শব্দ',

    // Corporate page
    'corporate.hero.title': 'B2B কর্পোরেট সমাধান',
    'corporate.hero.subtitle': 'প্রযুক্তি এবং ডেটা দিয়ে আপনার কোম্পানির সুস্থতা রূপান্তর করুন',
    'corporate.benefits.title': 'কেন XZenPress B2B বেছে নেবেন?',
    'corporate.benefits.compliance': 'আইনি সম্মতি',
    'corporate.benefits.compliance.desc': 'আইন 14.831/2024 এবং NR-1 এর সাথে সম্পূর্ণ সম্মতি',
    'corporate.benefits.roi': 'প্রমাণিত ROI',
    'corporate.benefits.roi.desc': '6 মাসে বিনিয়োগের রিটার্ন',
    'corporate.benefits.engagement': 'সম্পৃক্ততা',
    'corporate.benefits.engagement.desc': 'কর্মচারী সুস্থতায় 40% বৃদ্ধি',
    'corporate.benefits.certification': 'সার্টিফিকেশন',
    'corporate.benefits.certification.desc': 'মানসিক স্বাস্থ্য প্রচারকারী কোম্পানি সিল',
    'corporate.plans.title': 'কর্পোরেট পরিকল্পনা',
    'corporate.plans.subtitle': 'সব আকারের কোম্পানির জন্য সম্পূর্ণ সুস্থতা সমাধান',
    'corporate.analytics.title': 'B2B অ্যানালিটিক্স',
    'corporate.analytics.subtitle': 'কর্পোরেট সুস্থতা অপ্টিমাইজ করার জন্য ডেটা বুদ্ধিমত্তা',
    'corporate.roi.title': 'প্রমাণিত ROI',
    'corporate.roi.subtitle': 'XZenPress বাস্তবায়নকারী কোম্পানিগুলি রিপোর্ট করে:',
    'corporate.roi.stress': 'চাপ হ্রাস',
    'corporate.roi.absences': 'কম অনুপস্থিতি',
    'corporate.roi.engagement': 'উচ্চ সম্পৃক্ততা',
    'corporate.roi.return': 'বিনিয়োগের রিটার্ন',
    'corporate.contact.title': 'আপনার কোম্পানি রূপান্তর করতে প্রস্তুত?',
    'corporate.contact.subtitle': 'আমাদের বিশেষজ্ঞদের সাথে কথা বলুন এবং ব্যক্তিগত প্রস্তাব পান'
  },

  ru: {
    // Навигация
    'nav.home': 'Главная',
    'nav.acupressure': 'Акупрессура',
    'nav.breathing': 'Дыхание',
    'nav.premium': 'Премиум',
    'nav.corporate': 'Корпоративный',
    'nav.dashboard': 'Панель',
    'nav.sounds': 'Звуки',
    'nav.progress': 'Прогресс',
    'nav.personalization': 'Персонализация',
    'nav.login': 'Войти',
    'nav.logout': 'Выйти',

    // Главная
    'home.hero.title': 'Преобразите свою жизнь с помощью холистических терапий',
    'home.hero.subtitle': 'Преобразите свою жизнь с помощью холистических терапий, основанных на научных доказательствах',
    'home.hero.startNow': 'Начать сейчас',
    'home.hero.createAccount': 'Создать аккаунт',
    'home.features.title': 'Полные возможности',
    'home.features.subtitle': 'Все, что нужно для вашего благополучия',
    'home.feature.acupressure.title': 'TCM Акупрессура',
    'home.feature.acupressure.desc': '20 терапевтических точек традиционной китайской медицины',
    'home.feature.cranio.title': 'Краниопунктура',
    'home.feature.cranio.desc': 'Краниальные техники для памяти, концентрации и тревоги',
    'home.feature.breathing.title': 'Дыхание 4-7-8',
    'home.feature.breathing.desc': 'Научная техника с таймером и интегрированной хромотерапией',
    'home.feature.chromotherapy.title': 'Хромотерапия',
    'home.feature.chromotherapy.desc': 'Терапевтические цвета на основе нейронауки',
    'home.feature.sounds.title': 'Гармонизирующие звуки',
    'home.feature.sounds.desc': 'Полная библиотека + интеграция Spotify Premium',
    'home.feature.consultation.title': 'Консультации WhatsApp',
    'home.cta.title': 'Готовы начать?',
    'home.cta.subtitle': 'Присоединяйтесь к тысячам людей, меняющих свою жизнь',
    'home.cta.demo': 'Попробовать бесплатно',
    'home.cta.corporate': 'Корпоративные решения',
    'home.compliance.title': 'Корпоративное правовое соответствие',
    'home.compliance.subtitle': 'Полное соответствие бразильскому законодательству',

    // Acupressure page
    'acupressure.title': 'Интегрированная Терапия',
    'acupressure.subtitle': 'Акупрессура + Дыхание 4-7-8 + Хромотерапия + Гармонизирующие Звуки',
    'acupressure.categories.all': 'Все Точки',
    'acupressure.categories.general': 'Общая ТКМ',
    'acupressure.categories.cranio': 'Краниопунктура',
    'acupressure.categories.septicemia': 'Сепсис',
    'acupressure.categories.atm': 'ВНЧС',
    'acupressure.point.benefits': 'Для чего это',
    'acupressure.point.location': 'Расположение',
    'acupressure.point.instructions': 'Как применять',
    'acupressure.point.duration': 'Продолжительность',
    'acupressure.point.pressure': 'Давление',
    'acupressure.timer.active': 'Активная Терапия',
    'acupressure.timer.start': 'Начать Интегрированную Терапию',
    'acupressure.timer.stop': 'Остановить',
    'acupressure.timer.reset': 'Сброс',
    'acupressure.timer.switch': 'Переключиться на эту Точку',
    'acupressure.premium.unlock': 'Разблокировать Премиум',
    'acupressure.premium.exclusive': 'Премиум Точка',
    'acupressure.select.title': 'Выберите Точку',
    'acupressure.select.subtitle': 'Нажмите на любую точку, чтобы начать полную интегрированную терапию',
    'acupressure.integrated.description': 'Интегрированная Терапия: Точная акупрессура с таймером, Синхронизированное дыхание 4-7-8, Яркая хромотерапия, Опциональные гармонизирующие звуки',

    // Corporate page
    'corporate.hero.title': 'Корпоративные Решения B2B',
    'corporate.hero.subtitle': 'Преобразите благополучие вашей компании с помощью технологий и данных',
    'corporate.benefits.title': 'Почему выбрать XZenPress B2B?',
    'corporate.benefits.compliance': 'Правовое Соответствие',
    'corporate.benefits.compliance.desc': 'Полное соответствие Закону 14.831/2024 и НТ-1',
    'corporate.benefits.roi': 'Доказанная Рентабельность',
    'corporate.benefits.roi.desc': 'Возврат инвестиций за 6 месяцев',
    'corporate.benefits.engagement': 'Вовлеченность',
    'corporate.benefits.engagement.desc': '40% увеличение благополучия сотрудников',
    'corporate.benefits.certification': 'Сертификация',
    'corporate.benefits.certification.desc': 'Печать Компании Содействия Психическому Здоровью',
    'corporate.plans.title': 'Корпоративные Планы',
    'corporate.plans.subtitle': 'Полные решения благополучия для компаний всех размеров',
    'corporate.analytics.title': 'B2B Аналитика',
    'corporate.analytics.subtitle': 'Интеллект данных для оптимизации корпоративного благополучия',
    'corporate.roi.title': 'Доказанная Рентабельность',
    'corporate.roi.subtitle': 'Компании, внедрившие XZenPress, сообщают:',
    'corporate.roi.stress': 'Снижение стресса',
    'corporate.roi.absences': 'Меньше отсутствий',
    'corporate.roi.engagement': 'Более высокая вовлеченность',
    'corporate.roi.return': 'Возврат инвестиций',
    'corporate.contact.title': 'Готовы преобразить вашу компанию?',
    'corporate.contact.subtitle': 'Поговорите с нашими специалистами и получите персонализированное предложение'
  },

  ja: {
    // ナビゲーション
    'nav.home': 'ホーム',
    'nav.acupressure': '指圧',
    'nav.breathing': '呼吸',
    'nav.premium': 'プレミアム',
    'nav.corporate': '企業向け',
    'nav.dashboard': 'ダッシュボード',
    'nav.sounds': 'サウンド',
    'nav.progress': '進捗',
    'nav.personalization': 'パーソナライゼーション',
    'nav.login': 'ログイン',
    'nav.logout': 'ログアウト',

    // ホーム
    'home.hero.title': 'ホリスティック療法で人生を変える',
    'home.hero.subtitle': '科学的証拠に基づくホリスティック療法であなたの人生を変える',
    'home.hero.startNow': '今すぐ始める',
    'home.hero.createAccount': 'アカウント作成',
    'home.features.title': '完全な機能',
    'home.features.subtitle': 'あなたの健康に必要なすべて',
    'home.feature.acupressure.title': 'TCM指圧',
    'home.feature.acupressure.desc': '伝統中国医学の20の治療ポイント',
    'home.feature.cranio.title': '頭鍼療法',
    'home.feature.cranio.desc': '記憶、集中力、不安のための頭部技術',
    'home.feature.breathing.title': '4-7-8呼吸法',
    'home.feature.breathing.desc': 'タイマーと統合色彩療法を備えた科学的技術',
    'home.feature.chromotherapy.title': '色彩療法',
    'home.feature.chromotherapy.desc': '神経科学に基づく治療色',
    'home.feature.sounds.title': '調和音',
    'home.feature.sounds.desc': '完全ライブラリ + Spotify Premium統合',
    'home.feature.consultation.title': 'WhatsApp相談',
    'home.cta.title': '始める準備はできましたか？',
    'home.cta.subtitle': '人生を変えている何千人もの人々に参加してください',
    'home.cta.demo': '無料で試す',
    'home.cta.corporate': '企業ソリューション',
    'home.compliance.title': '企業法的コンプライアンス',
    'home.compliance.subtitle': 'ブラジル法との完全な準拠',

    // Acupressure page
    'acupressure.title': '統合療法',
    'acupressure.subtitle': '指圧 + 4-7-8呼吸法 + 色彩療法 + 調和音',
    'acupressure.categories.all': '全てのポイント',
    'acupressure.categories.general': '一般TCM',
    'acupressure.categories.cranio': '頭蓋鍼',
    'acupressure.categories.septicemia': '敗血症',
    'acupressure.categories.atm': '顎関節症',
    'acupressure.point.benefits': '効果',
    'acupressure.point.location': '位置',
    'acupressure.point.instructions': '適用方法',
    'acupressure.point.duration': '持続時間',
    'acupressure.point.pressure': '圧力',
    'acupressure.timer.active': 'アクティブ療法',
    'acupressure.timer.start': '統合療法を開始',
    'acupressure.timer.stop': '停止',
    'acupressure.timer.reset': 'リセット',
    'acupressure.timer.switch': 'このポイントに切り替え',
    'acupressure.premium.unlock': 'プレミアム解除',
    'acupressure.premium.exclusive': 'プレミアムポイント',
    'acupressure.select.title': 'ポイントを選択',
    'acupressure.select.subtitle': '完全な統合療法を開始するには任意のポイントをクリック',
    'acupressure.integrated.description': '統合療法：精密タイマー指圧、同期4-7-8呼吸、鮮やかな色彩療法、オプション調和音',

    // Corporate page
    'corporate.hero.title': 'B2B企業ソリューション',
    'corporate.hero.subtitle': 'テクノロジーとデータで会社のウェルネスを変革',
    'corporate.benefits.title': 'なぜXZenPress B2Bを選ぶのか？',
    'corporate.benefits.compliance': '法的コンプライアンス',
    'corporate.benefits.compliance.desc': '法律14.831/2024とNR-1への完全準拠',
    'corporate.benefits.roi': '実証済みROI',
    'corporate.benefits.roi.desc': '6ヶ月での投資収益率',
    'corporate.benefits.engagement': 'エンゲージメント',
    'corporate.benefits.engagement.desc': '従業員ウェルネス40%向上',
    'corporate.benefits.certification': '認証',
    'corporate.benefits.certification.desc': 'メンタルヘルス促進企業シール',
    'corporate.plans.title': '企業プラン',
    'corporate.plans.subtitle': 'あらゆる規模の企業向け完全ウェルネスソリューション',
    'corporate.analytics.title': 'B2Bアナリティクス',
    'corporate.analytics.subtitle': '企業ウェルネス最適化のためのデータインテリジェンス',
    'corporate.roi.title': '実証済みROI',
    'corporate.roi.subtitle': 'XZenPressを実装した企業の報告：',
    'corporate.roi.stress': 'ストレス軽減',
    'corporate.roi.absences': '欠勤減少',
    'corporate.roi.engagement': 'エンゲージメント向上',
    'corporate.roi.return': '投資収益率',
    'corporate.contact.title': '会社を変革する準備はできましたか？',
    'corporate.contact.subtitle': '専門家と話し、パーソナライズされた提案を受け取る'
  },

  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.acupressure': 'Akupressur',
    'nav.breathing': 'Atmung',
    'nav.premium': 'Premium',
    'nav.corporate': 'Unternehmen',
    'nav.dashboard': 'Dashboard',
    'nav.sounds': 'Klänge',
    'nav.progress': 'Fortschritt',
    'nav.personalization': 'Personalisierung',
    'nav.login': 'Anmelden',
    'nav.logout': 'Abmelden',

    // Startseite
    'home.hero.title': 'Verwandeln Sie Ihr Leben mit ganzheitlichen Therapien',
    'home.hero.subtitle': 'Verwandeln Sie Ihr Leben mit evidenzbasierten ganzheitlichen Therapien',
    'home.hero.startNow': 'Jetzt beginnen',
    'home.hero.createAccount': 'Konto erstellen',
    'home.features.title': 'Vollständige Funktionen',
    'home.features.subtitle': 'Alles was Sie für Ihr Wohlbefinden brauchen',
    'home.feature.acupressure.title': 'TCM Akupressur',
    'home.feature.acupressure.desc': '20 therapeutische Punkte der Traditionellen Chinesischen Medizin',
    'home.feature.cranio.title': 'Kraniopunktur',
    'home.feature.cranio.desc': 'Schädeltechniken für Gedächtnis, Konzentration und Angst',
    'home.feature.breathing.title': '4-7-8 Atmung',
    'home.feature.breathing.desc': 'Wissenschaftliche Technik mit Timer und integrierter Farbtherapie',
    'home.feature.chromotherapy.title': 'Farbtherapie',
    'home.feature.chromotherapy.desc': 'Therapeutische Farben basierend auf Neurowissenschaft',
    'home.feature.sounds.title': 'Harmonisierende Klänge',
    'home.feature.sounds.desc': 'Vollständige Bibliothek + Spotify Premium Integration',
    'home.feature.consultation.title': 'WhatsApp Beratungen',
    'home.cta.title': 'Bereit anzufangen?',
    'home.cta.subtitle': 'Schließen Sie sich Tausenden von Menschen an, die ihr Leben verändern',
    'home.cta.demo': 'Kostenlos testen',
    'home.cta.corporate': 'Unternehmenslösungen',
    'home.compliance.title': 'Unternehmens-Rechtskonformität',
    'home.compliance.subtitle': 'Vollständige Einhaltung der brasilianischen Gesetzgebung',

    // Acupressure page
    'acupressure.title': 'Integrierte Therapie',
    'acupressure.subtitle': 'Akupressur + 4-7-8-Atmung + Farbtherapie + Harmonisierende Klänge',
    'acupressure.categories.all': 'Alle Punkte',
    'acupressure.categories.general': 'Allgemeine TCM',
    'acupressure.categories.cranio': 'Kraniopunktur',
    'acupressure.categories.septicemia': 'Sepsis',
    'acupressure.categories.atm': 'Kiefergelenk',
    'acupressure.point.benefits': 'Wofür es ist',
    'acupressure.point.location': 'Lage',
    'acupressure.point.instructions': 'Wie anwenden',
    'acupressure.point.duration': 'Dauer',
    'acupressure.point.pressure': 'Druck',
    'acupressure.timer.active': 'Aktive Therapie',
    'acupressure.timer.start': 'Integrierte Therapie Starten',
    'acupressure.timer.stop': 'Stoppen',
    'acupressure.timer.reset': 'Zurücksetzen',
    'acupressure.timer.switch': 'Zu diesem Punkt Wechseln',
    'acupressure.premium.unlock': 'Premium Freischalten',
    'acupressure.premium.exclusive': 'Premium Punkt',
    'acupressure.select.title': 'Punkt Auswählen',
    'acupressure.select.subtitle': 'Klicken Sie auf einen beliebigen Punkt, um die vollständige integrierte Therapie zu starten',
    'acupressure.integrated.description': 'Integrierte Therapie: Präzise Timer-Akupressur, Synchronisierte 4-7-8-Atmung, Lebendige Farbtherapie, Optionale harmonisierende Klänge',

    // Corporate page
    'corporate.hero.title': 'B2B Unternehmenslösungen',
    'corporate.hero.subtitle': 'Verwandeln Sie das Wohlbefinden Ihres Unternehmens mit Technologie und Daten',
    'corporate.benefits.title': 'Warum XZenPress B2B wählen?',
    'corporate.benefits.compliance': 'Rechtliche Compliance',
    'corporate.benefits.compliance.desc': 'Vollständige Einhaltung von Gesetz 14.831/2024 und NR-1',
    'corporate.benefits.roi': 'Bewiesener ROI',
    'corporate.benefits.roi.desc': 'Kapitalrendite in 6 Monaten',
    'corporate.benefits.engagement': 'Engagement',
    'corporate.benefits.engagement.desc': '40% Steigerung des Mitarbeiterwohlbefindens',
    'corporate.benefits.certification': 'Zertifizierung',
    'corporate.benefits.certification.desc': 'Siegel für Mental Health Förderunternehmen',
    'corporate.plans.title': 'Unternehmenspläne',
    'corporate.plans.subtitle': 'Vollständige Wellness-Lösungen für Unternehmen aller Größen',
    'corporate.analytics.title': 'B2B Analytics',
    'corporate.analytics.subtitle': 'Datenintelligenz zur Optimierung des Unternehmenswohlbefindens',
    'corporate.roi.title': 'Bewiesener ROI',
    'corporate.roi.subtitle': 'Unternehmen, die XZenPress implementiert haben, berichten:',
    'corporate.roi.stress': 'Stressreduktion',
    'corporate.roi.absences': 'Weniger Fehlzeiten',
    'corporate.roi.engagement': 'Höheres Engagement',
    'corporate.roi.return': 'Kapitalrendite',
    'corporate.contact.title': 'Bereit, Ihr Unternehmen zu transformieren?',
    'corporate.contact.subtitle': 'Sprechen Sie mit unseren Spezialisten und erhalten Sie ein personalisiertes Angebot'
  },

  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.acupressure': 'Acupression',
    'nav.breathing': 'Respiration',
    'nav.premium': 'Premium',
    'nav.corporate': 'Entreprise',
    'nav.dashboard': 'Tableau de bord',
    'nav.sounds': 'Sons',
    'nav.progress': 'Progrès',
    'nav.personalization': 'Personnalisation',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',

    // Accueil
    'home.hero.title': 'Transformez votre vie avec des thérapies holistiques',
    'home.hero.subtitle': 'Transmuter avec des thérapies intégrateur basées sur des preuves scientifiques',
    'home.hero.startNow': 'Commencer maintenant',
    'home.hero.createAccount': 'Créer un compte',
    'home.features.title': 'Fonctionnalités complètes',
    'home.features.subtitle': 'Tout ce dont vous avez besoin pour votre bien-être',
    'home.feature.acupressure.title': 'Acupression MTC',
    'home.feature.acupressure.desc': '20 points thérapeutiques de Médecine Traditionnelle Chinoise',
    'home.feature.cranio.title': 'Craniopuncture',
    'home.feature.cranio.desc': 'Techniques crâniennes pour mémoire, concentration et anxiété',
    'home.feature.breathing.title': 'Respiration 4-7-8',
    'home.feature.breathing.desc': 'Technique scientifique avec minuteur et chromothérapie intégrée',
    'home.feature.chromotherapy.title': 'Chromothérapie',
    'home.feature.chromotherapy.desc': 'Couleurs thérapeutiques basées sur les neurosciences',
    'home.feature.sounds.title': 'Sons harmonisants',
    'home.feature.sounds.desc': 'Bibliothèque complète + intégration Spotify Premium',
    'home.feature.consultation.title': 'Consultations WhatsApp',
    'home.cta.title': 'Prêt à commencer?',
    'home.cta.subtitle': 'Rejoignez des milliers de personnes transformant leur vie',
    'home.cta.demo': 'Essayer gratuitement',
    'home.cta.corporate': 'Solutions d\'entreprise',
    'home.compliance.title': 'Conformité légale d\'entreprise',
    'home.compliance.subtitle': 'Conformité complète avec la législation brésilienne',

    // Acupressure page
    'acupressure.title': 'Thérapie Intégrée',
    'acupressure.subtitle': 'Acupression + Respiration 4-7-8 + Chromothérapie + Sons Harmonisants',
    'acupressure.categories.all': 'Tous les Points',
    'acupressure.categories.general': 'MTC Général',
    'acupressure.categories.cranio': 'Craniopuncture',
    'acupressure.categories.septicemia': 'Septicémie',
    'acupressure.categories.atm': 'ATM',
    'acupressure.point.benefits': 'À quoi ça sert',
    'acupressure.point.location': 'Emplacement',
    'acupressure.point.instructions': 'Comment appliquer',
    'acupressure.point.duration': 'Durée',
    'acupressure.point.pressure': 'Pression',
    'acupressure.timer.active': 'Thérapie Active',
    'acupressure.timer.start': 'Commencer Thérapie Intégrée',
    'acupressure.timer.stop': 'Arrêter',
    'acupressure.timer.reset': 'Réinitialiser',
    'acupressure.timer.switch': 'Passer à ce Point',
    'acupressure.premium.unlock': 'Débloquer Premium',
    'acupressure.premium.exclusive': 'Point Premium',
    'acupressure.select.title': 'Sélectionner un Point',
    'acupressure.select.subtitle': 'Cliquez sur n\'importe quel point pour commencer la thérapie intégrée complète',
    'acupressure.integrated.description': 'Thérapie Intégrée : Acupression avec minuteur précis, Respiration 4-7-8 synchronisée, Chromothérapie vibrante, Sons harmonisants optionnels',

    // Corporate page
    'corporate.hero.title': 'Solutions d\'Entreprise B2B',
    'corporate.hero.subtitle': 'Transformez le bien-être de votre entreprise avec la technologie et les données',
    'corporate.benefits.title': 'Pourquoi choisir XZenPress B2B ?',
    'corporate.benefits.compliance': 'Conformité Légale',
    'corporate.benefits.compliance.desc': 'Conformité complète avec la Loi 14.831/2024 et NR-1',
    'corporate.benefits.roi': 'ROI Prouvé',
    'corporate.benefits.roi.desc': 'Retour sur investissement en 6 mois',
    'corporate.benefits.engagement': 'Engagement',
    'corporate.benefits.engagement.desc': '40% d\'augmentation du bien-être des employés',
    'corporate.benefits.certification': 'Certification',
    'corporate.benefits.certification.desc': 'Sceau d\'Entreprise Promotrice de Santé Mentale',
    'corporate.plans.title': 'Plans d\'Entreprise',
    'corporate.plans.subtitle': 'Solutions de bien-être complètes pour entreprises de toutes tailles',
    'corporate.analytics.title': 'Analytics B2B',
    'corporate.analytics.subtitle': 'Intelligence de données pour optimiser le bien-être d\'entreprise',
    'corporate.roi.title': 'ROI Prouvé',
    'corporate.roi.subtitle': 'Les entreprises qui ont implémenté XZenPress rapportent :',
    'corporate.roi.stress': 'Réduction du stress',
    'corporate.roi.absences': 'Moins d\'absences',
    'corporate.roi.engagement': 'Engagement plus élevé',
    'corporate.roi.return': 'Retour sur investissement',
    'corporate.contact.title': 'Prêt à transformer votre entreprise ?',
    'corporate.contact.subtitle': 'Parlez à nos spécialistes et recevez une proposition personnalisée'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]); // Português como padrão

  useEffect(() => {
    // Carregar idioma salvo ou detectar idioma do navegador
    const savedLanguage = localStorage.getItem('xzenpress_language');
    if (savedLanguage) {
      const found = languages.find(lang => lang.code === savedLanguage);
      if (found) {
        setCurrentLanguage(found);
        return;
      }
    }

    // Detectar idioma do navegador
    const browserLang = navigator.language.split('-')[0];
    const detected = languages.find(lang => lang.code === browserLang);
    if (detected) {
      setCurrentLanguage(detected);
    }
  }, []);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('xzenpress_language', language.code);
    
    // Atualizar direção do texto para idiomas RTL
    document.documentElement.dir = language.direction;
    document.documentElement.lang = language.code;
  };

  const t = (key: string): string => {
    const translation = translations[currentLanguage.code]?.[key];
    if (translation) {
      return translation;
    }
    
    // Fallback para português se a tradução não existir
    const fallback = translations.pt[key];
    if (fallback) {
      return fallback;
    }
    
    // Se nem o fallback existir, retornar a chave
    console.warn(`Translation missing for key: ${key} in language: ${currentLanguage.code}`);
    return key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};